apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: api
          image: gitlab.sciences-po.fr:4567/medialab/bhht-datascape/bhht-api:latest
          env:
            - name: ES_HOST
              value: bhht-index.bhht.svc.cluster.local
          imagePullPolicy: Always
