apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  replicas: 1
  selector:
    matchLabels:
      component: index
  template:
    metadata:
      labels:
        component: index
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
        - name: index
          image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
          env:
            - name: xpack.monitoring.enabled
              value: 'false'
            - name: bootstrap.memory_lock
              value: 'false'
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.watcher.enabled
              value: 'false'
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          volumeMounts:
            - name: index-vol
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: index-vol
          persistentVolumeClaim:
            claimName: index-pvc
