version: '2'
services:
  client:
    build: client
    restart: unless-stopped
    links:
      - api
    ports:
      - 80:80
    volumes_from:
      - api
  api:
    build: .
    restart: unless-stopped
    links:
      - index
    ports:
      - 4000:4000
  index:
    image: elasticsearch:5.2.2-alpine
    restart: unless-stopped
    ports:
      - 9200:9200
