apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: client
          image: gitlab.sciences-po.fr:4567/medialab/bhht-datascape/bhht-client:latest
          env:
            - name: API_HOST
              value: bhht-api.bhht.svc.cluster.local
            - name: API_PORT
              value: '4000'
          imagePullPolicy: Always
