apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bhht

namePrefix: bhht-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: htpasswd
  files:
    - auth

images:
  - name: gitlab.sciences-po.fr:4567/medialab/bhht-datascape/bhht-api
    newTag: 'staging'
  - name: gitlab.sciences-po.fr:4567/medialab/bhht-datascape/bhht-client
    newTag: 'staging'
